version: "3.3"

services:
  ideno_server:
    image: 'registry.setilic.com/ideno/server:latest'
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      - "DATABASE_URL=sqlite:///usr/src/ideno/.temp/ideno.db"
      - "CORS_ORIGIN=http://localhost:3000"
      - "PORT=5000"


  ideno_client:
    image: 'registry.setilic.com/ideno/client:latest'
    ports:
      - "127.0.0.1:3000:3000"
