import './globals.css';
import type { Metadata } from 'next';
import { ReactNode } from 'react';
import { inter } from '@/fonts';
import { Providers } from '@/app/_components/providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang='en'>
      <Providers>
        <body className={inter.className}>
          <main>{children}</main>
        </body>
      </Providers>
    </html>
  );
}
